### ISSUE TITLE
Proper way to add additional packages to the virtualenv?

### ISSUE THREAD

**Issue by Ramblurr** [smartgic/ansible-role-mycroft#1]
Great role! I'm using it as a base for my house's mycroft deployment.

I would like to use the mimic3 TTS plugin, which requires installing some deps in the virtualenv. I looked through the role code, but don't see an easy extension point.

Is this possible as is (or is this a feature request)?

**Comment by goldyfruit** [comment]
Hi @Ramblurr,

I added the `mycroft_pip_custom_libraries` variable which is a YAML list, you should be able to add Python libraries from PyPi or `git`.

Let me know if it works for you.
